
export const GET_PRODUCTS = 'GET_PRODUCTS';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const CHOOSED_PRODUCT = 'CHOOSED_PRODUCT';

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
